# Generated by Django 4.0.4 on 2022-04-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('reservation_id', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_payer', models.IntegerField(default=0)),
                ('moyen_paiement', models.CharField(choices=[('1', 'Carte de crédit'), ('2', 'Mobile monney'), ('3', 'Compte banquaire')], max_length=60)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=60)),
                ('nombre_place_libre', models.IntegerField(default=0)),
                ('nombre_place_occuper', models.IntegerField(default=0)),
                ('nombre_place_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stationnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.IntegerField(default=0)),
                ('heure_entrer', models.DateTimeField(auto_now_add=True, verbose_name="Heur d'entré")),
                ('status_stationnement', models.BooleanField(default=True)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True, verbose_name='heur de sortie')),
                ('m_Paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.paiement')),
                ('m_Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.parking')),
                ('m_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_place', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('m_Paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.paiement')),
                ('m_Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.parking')),
                ('m_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guichet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('m_Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_abonnement', models.DateTimeField(auto_now_add=True)),
                ('date_fin_abonnement', models.DateTimeField(blank=True, null=True)),
                ('status_abonnement', models.BooleanField(default=True)),
                ('type_abonnement', models.CharField(choices=[('1', 'Mensuel'), ('3', 'Trimestriel'), ('6', 'Semestriel'), ('12', 'Annuel')], max_length=30)),
                ('m_Paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.paiement')),
                ('m_Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.parking')),
                ('m_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
