# Generated by Django 4.0.4 on 2022-04-27 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0002_parking_etat_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stationnement',
            name='heure_entrer',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Heure d'entré"),
        ),
        migrations.AlterField(
            model_name='stationnement',
            name='heure_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='heure de sortie'),
        ),
    ]
