# Generated by Django 4.0.4 on 2022-04-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0003_reservation_date_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='places_octroyer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
