# Generated by Django 4.0.4 on 2022-04-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0004_reservation_places_octroyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationnement',
            name='m_Paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systeme.paiement'),
        ),
    ]
