# Generated by Django 4.0.4 on 2022-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0005_alter_stationnement_m_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion_reservation',
            name='qr_code',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestion_reservation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='codeqr'),
        ),
    ]
