# Generated by Django 4.0.4 on 2022-05-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0006_gestion_reservation_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='m_Paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systeme.paiement'),
        ),
    ]
