# Generated by Django 4.0.4 on 2022-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0007_alter_reservation_m_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
