# Generated by Django 4.0.4 on 2022-05-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0008_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_reservation',
            name='qr_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gestion_reservation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='reserv_code_qr'),
        ),
        migrations.AlterField(
            model_name='gestion_reservation',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeme.reservation'),
        ),
    ]
