# Generated by Django 4.0.4 on 2022-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0009_alter_gestion_reservation_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nombre_place',
            field=models.IntegerField(default=1),
        ),
    ]
