# Generated by Django 4.0.4 on 2022-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0011_alter_abonnement_m_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='status_abonnement',
            field=models.BooleanField(default=False),
        ),
    ]
