# Generated by Django 4.0.4 on 2022-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0012_alter_abonnement_status_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('0', '---------'), ('1', 'Mensuel'), ('3', 'Trimestriel'), ('6', 'Semestriel'), ('12', 'Annuel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(max_length=60),
        ),
    ]
