# Generated by Django 4.0.4 on 2022-05-07 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0013_paiement_numero_alter_abonnement_type_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationnement',
            name='heure_entrer',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name="Heure d'entré"),
        ),
    ]
