# Generated by Django 4.0.4 on 2022-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0013_paiement_numero_alter_abonnement_type_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
