# Generated by Django 4.0.4 on 2022-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0013_alter_abonnement_type_abonnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_tel',
            field=models.IntegerField(default=0),
        ),
    ]
