# Generated by Django 4.0.4 on 2022-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0014_alter_abonnement_date_fin_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_reservation',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='reserv_code_qr'),
        ),
    ]
