# Generated by Django 4.0.4 on 2022-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0015_alter_gestion_reservation_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationnement',
            name='qr_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
