# Generated by Django 4.0.4 on 2022-05-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systeme', '0013_alter_abonnement_type_abonnement'),
        ('systeme', '0016_stationnement_qr_code'),
    ]

    operations = [
    ]
